### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by csokaimola** [csokaimola/book-pilot#3]
- with CSS (https://www.w3schools.com/css/default.asp)
- bootstrap css: https://getbootstrap.com/docs/4.3/components/alerts/
- Mate's website (for basic formatting)
- should be mobile optimized (its easy in bootstrap css, called "responsiveness")
- check existing templates
- jekyll

**Comment by csokaimola** [comment]
-  viridis colour palette
- font : same as in book

**Comment by csokaimola** [comment]
- embed separate html files
- picture of book cover
- downloadable pdf
- downloadable data (and link to github repos for github users, and short how-to description)
- pictures of authors with short bio
- 3 pictures of "what's more" (case studies /data viz/ big data)

**Comment by csokaimola** [comment]
Menu:
1. Home (4 pictures (with 1 sentence each) in squares for the 4 parts . Click: link to the respective part in second menu page "Key topics")
2. Key topics
3. Data & Code
4. Buy this book

**Comment by data-analysis-textbook** [comment]
Esetleg lehetne:

Home
- summary text, allando
Why this textbook? - ez lehetne a "blog" formátum
- audience
- what is special
- endorsements
Details 
- key topics
- chapter list
Data and code

külön legyen valahol egy Buy this book gomb:-)

**Comment by data-analysis-textbook** [comment]
ahh, és még 1.

legyen egy blog fül is, mert az lesz. valszeg nem itt, de itt is lesz rá valami.
