### ISSUE TITLE
Dependency management (Julcsi)

### ISSUE THREAD

**Issue by csokaimola** [csokaimola/book-pilot#9]
How does it wor in R? (like requirements.txt in Python) (for stata its no problem)

**Comment by csokaimola** [comment]
(basic solution: at the beginning of the code write package in comment. If new version is used, rewrite code, which is version controlled on git)

**Comment by julcsii** [comment]
You can't specify version in `install.packages()`, but you need another function:
```R
require(devtools)
install_version("ggplot2", version = "0.9.1", repos = "http://cran.us.r-project.org")
```

More details: https://stackoverflow.com/questions/17082341/installing-older-version-of-r-package

**Comment by julcsii** [comment]
We could put in each repo an R script to download all the packages with an explicit version and define the versions in a config file?

**Comment by csokaimola** [comment]
Like in ch00_tech_prep folder

**Comment by csokaimola** [comment]
Like in ch00_tech_prep folder [here] (https://www.dropbox.com/scl/fo/wnuunoqs8qsx0jwrckobd/AACyCNvuB_JSegNVsOohsqcia/ch00_tech_prep?dl=0&subfolder_nav_tracking=1)
